version: '3'
services:
  web-app:
    build:
      context: .
    ports:
      -  "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  smtp-server:
    build:
      context: .
    volumes:
      - .:/app
    command: python smtp-server.py

  database:
    image: postgres:15.1-alpine
    env_file:
      - .env
#
#  test-database:
#    image: postgres:15.1-alpine
#    env_file:
#      - .env

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    restart: always

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - database
    env_file:
      - .env

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "5555:5555"
