version: '3'
services:
  web-app:
    build:
      context: .
    ports:
      -  "8000:8000"
    volumes:
      - .:/app

    environment:
      - DB_HOST=database
      - DB_NAME=equipment_db
      - DB_USER=postgres
      - DB_PASS=1234
      - DJANGO_SETTINGS_MODULE=equipment_rental_site.settings

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database
    restart: "always"

  smtp-server:
    build:
      context: .
    volumes:
      - .:/app
    command: python smtp-server.py
    restart: "always"

  database:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=equipment_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    restart: "always"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    restart: "always"

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=equipment_db
      - DB_USER=postgres
      - DB_PASS=1234
    restart: "always"

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "5555:5555"
    restart: "always"
