version: '3'
services:
  web-app:
    build:
      context: .
    container_name: django
    ports:
      -  "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  # smtp-server:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/app
  #   command: python smtp-server.py

  database:
    image: postgres:15.1-alpine
    env_file:
      - .env

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    restart: always

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - database
    env_file:
      - .env

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "5555:5555"

  frontend:
    build: ./frontend
    container_name: react
    restart: always
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - web-app
    volumes:
      - ./frontend/public/:/usr/src/app/public/
      - ./frontend/src/:/usr/src/app/src/

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - frontend
      - web-app
    volumes:
      - ./static:/home/src/app/static/
      - ./media:/home/src/app/media/