version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django
    expose:
      - 8000
    volumes:
      - .:/app
    env_file:
      - .env.prod
    command: gunicorn equipment_rental_site.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - database

  database:
    image: postgres:15.1-alpine
    container_name: rental_db
    env_file:
      - .env.prod

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    restart: always

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - database
    env_file:
      - .env.prod

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "5555:5555"

  frontend:
    build: ./frontend
    container_name: react
    ports:
      - 80:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/public/:/usr/src/app/public/
      - ./frontend/src/:/usr/src/app/src/


  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./static:/home/src/app/static/
      - ./media:/home/src/app/media/
