# Generated by Django 4.2 on 2023-06-30 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('idempotence_key', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='Created')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=36)),
                ('idempotence_key', models.CharField(max_length=36)),
                ('date_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_currency', models.CharField(max_length=3)),
                ('income_amount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_amount_currency', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
