# Generated by Django 4.2 on 2023-06-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createdpayment',
            old_name='user',
            new_name='user_id',
        ),
    ]
