# Generated by Django 4.2 on 2023-05-17 13:05

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date_created', models.DateField()),
                ('rate', models.PositiveSmallIntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)])),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=feedback.models.upload_path)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.feedback')),
            ],
        ),
    ]
