# Generated by Django 4.2 on 2023-06-30 07:32

from django.db import migrations, models
import django.db.models.deletion
import services.equipment.upload_photos_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=services.equipment.upload_photos_path.upload_path)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_photo', to='feedback.feedback')),
            ],
        ),
    ]
