# Generated by Django 4.2 on 2023-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_delete_rental_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackphoto',
            old_name='equipment',
            new_name='feedback',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
