# Generated by Django 4.2 on 2023-05-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
