# Generated by Django 4.2 on 2023-05-19 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_added',
        ),
        migrations.AddField(
            model_name='cart',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
