name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        echo "$RENTAL_PROD_ENV" > .env
        docker-compose up -d

    - name: Wait for Django to start
      run: |
        until docker logs -f django | grep "Creating django"; do
          echo "Waiting for Django to start..."
          sleep 5
        done

    - name: Run Tests
      run: |
        if docker exec -it django sh -c "pytest"; then
          echo "Tests passed successfully"
        else
          echo "Tests failed"
          exit 1
        fi

    - name: Stop containers
      run: |
        docker-compose down
        
Creating rental_site_redis_1 ... 
Creating rental_site_database_1 ... 
Creating rental_site_database_1 ... done
Creating django                 ... 
Creating rental_site_redis_1    ... done
Creating rental_site_worker_1   ... 
Creating rental_site_flower_1   ... 
Creating rental_site_flower_1   ... done
Creating django                 ... done
Creating react                  ... 
Creating rental_site_worker_1   ... done
Creating react                  ... done
Creating rental_site_nginx_1    ... 
Creating rental_site_nginx_1    ... done
