name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} > .env.prod
        echo YOOKASSA_ACCOUNT_ID=${{ secrets.YOOKASSA_ACCOUNT_ID }} >> .env.prod
        echo YOOKASSA_SECRET_KEY=${{ secrets.YOOKASSA_SECRET_KEY }} >> .env.prod
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env.prod
        echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env.prod
        echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env.prod
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env.prod
        echo CORS_BACKEND_ADDRESS=${{ secrets.CORS_BACKEND_ADDRESS }} >> .env.prod
        echo BACKEND_SERVER_IP=${{ secrets.BACKEND_SERVER_IP }} >> .env.prod
        echo BACKEND_SERVER_PORT=${{ secrets.BACKEND_SERVER_PORT }} >> .env.prod
        echo DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }} >> .env.prod

    - name: Debug env
      run: |
        cat .env.prod

    - name: run containers
      run: docker-compose -f docker-compose.ci.yml up --build -d
      
    - name: Sleep for 10 seconds
      run: sleep 15
      
    - name: Wait for Database to Start
      run: |
        max_attempts=3
        attempts=0
        until nc -zv rental_db 5432 || [ $attempts -eq $max_attempts ]; do
          echo "Waiting for the database to start..."
          sleep 2
          attempts=$((attempts + 1))
        done
        
    - name: Sleep for 5 seconds
      run: sleep 5
      
    - name: makemigrations
      run: docker exec django sh -c "python manage.py makemigrations"

    - name: Sleep for 5 seconds
      run: sleep 5

    - name: migrate
      run: docker exec django sh -c "python manage.py migrate"

    - name: Sleep for 5 seconds
      run: sleep 5
        
    - name: Run Tests
      run: |
        if docker exec django sh -c "pytest"; then
          echo "Tests passed successfully"
        else
          echo "Tests failed"
          exit 1
        fi

  check_pep8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.7

    - name: Install PEP 8 linter
      run: pip install flake8

    - name: Run PEP 8 linter
      run: flake8

    - name: Check PEP 8 results
      run: |
        if [ $? -eq 0 ]; then
          echo "PEP 8 check passed successfully"
        else
          echo "PEP 8 check failed"
          exit 1
        fi

